namespace DotnetCoupling.Cli.Analysis;

internal static class FileDiscovery
{
    private static readonly string[] ExcludedDirectoryNames = [".git", ".vs", "bin", "obj"];

    internal static string[] DiscoverCSharpFiles(string fullPath)
    {
        if (File.Exists(fullPath) && fullPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            return IsGeneratedFile(fullPath) ? [] : [fullPath];
        }

        if (!Directory.Exists(fullPath))
        {
            return [];
        }

        return Directory.EnumerateFiles(fullPath, "*.cs", SearchOption.AllDirectories)
            .Where(file => !IsExcludedPath(file) && !IsGeneratedFile(file))
            .Order(StringComparer.Ordinal)
            .ToArray();
    }

    internal static bool IsExcludedPath(string file)
    {
        string[] segments = file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return segments.Any(segment => ExcludedDirectoryNames.Contains(segment, StringComparer.OrdinalIgnoreCase));
    }

    internal static bool IsGeneratedFile(string file)
    {
        string fileName = Path.GetFileName(file);
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        using StreamReader reader = File.OpenText(file);
        for (int i = 0; i < 5 && !reader.EndOfStream; i++)
        {
            string? line = reader.ReadLine();
            if (line is not null && line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
