namespace DotnetCoupling.Cli.Analysis;

internal static class FileDiscovery
{
    private static readonly string[] ExcludedDirectoryNames = [".git", ".vs", "bin", "obj"];

    internal static string[] DiscoverCSharpFiles(string fullPath, AnalysisOptions? options = null)
    {
        options ??= AnalysisOptions.Default;
        if (File.Exists(fullPath) && fullPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            return IsGeneratedFile(fullPath) || IsIgnoredByPattern(fullPath, options.ExcludePathPatterns) ? [] : [fullPath];
        }

        if (!Directory.Exists(fullPath))
        {
            return [];
        }

        return Directory.EnumerateFiles(fullPath, "*.cs", SearchOption.AllDirectories)
            .Where(file => !IsExcludedPath(file) && !IsGeneratedFile(file) && !IsIgnoredByPattern(file, options.ExcludePathPatterns))
            .Order(StringComparer.Ordinal)
            .ToArray();
    }

    internal static bool IsExcludedPath(string file)
    {
        string[] segments = file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return segments.Any(segment => ExcludedDirectoryNames.Contains(segment, StringComparer.OrdinalIgnoreCase));
    }

    internal static bool IsGeneratedFile(string file)
    {
        string fileName = Path.GetFileName(file);
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        using StreamReader reader = File.OpenText(file);
        for (int i = 0; i < 5 && !reader.EndOfStream; i++)
        {
            string? line = reader.ReadLine();
            if (line is not null && line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    internal static bool IsIgnoredByPattern(string file, IReadOnlyList<string> patterns)
    {
        string normalizedFile = file.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');
        foreach (string pattern in patterns)
        {
            string normalizedPattern = pattern.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');
            if (MatchesPattern(normalizedFile, normalizedPattern))
            {
                return true;
            }
        }

        return false;
    }

    private static bool MatchesPattern(string normalizedFile, string normalizedPattern)
    {
        if (normalizedPattern.StartsWith("**/", StringComparison.Ordinal))
        {
            string suffix = normalizedPattern[3..];
            if (suffix.StartsWith("*.", StringComparison.Ordinal))
            {
                return normalizedFile.EndsWith(suffix[1..], StringComparison.OrdinalIgnoreCase);
            }

            return normalizedFile.Contains("/" + suffix.TrimEnd('/'), StringComparison.OrdinalIgnoreCase)
                || normalizedFile.EndsWith(suffix.TrimEnd('/'), StringComparison.OrdinalIgnoreCase);
        }

        if (normalizedPattern.Contains('*', StringComparison.Ordinal))
        {
            string[] parts = normalizedPattern.Split('*', StringSplitOptions.RemoveEmptyEntries);
            int index = 0;
            foreach (string part in parts)
            {
                int found = normalizedFile.IndexOf(part, index, StringComparison.OrdinalIgnoreCase);
                if (found < 0)
                {
                    return false;
                }

                index = found + part.Length;
            }

            return true;
        }

        return normalizedFile.Contains(normalizedPattern, StringComparison.OrdinalIgnoreCase);
    }
}
