using DotnetCoupling.Cli.Analysis;
using Xunit;

namespace DotnetCoupling.Tests;

public sealed class CSharpDependencyAnalyzerTests
{
    [Fact]
    public void Analyze_TwoTypesWithConstructorDependency_ReportsComponentAndCoupling()
    {
        string directory = CreateFixture("""
            namespace Sample.App;

            public sealed class Handler
            {
                public Handler(IRepository repository)
                {
                }
            }

            public interface IRepository
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(2, report.Components.Count);
        Assert.Contains(report.Couplings, coupling =>
            coupling.Source == "Sample.App.Handler"
            && coupling.Target == "Sample.App.IRepository"
            && coupling.Strength == IntegrationStrength.Contract);
    }

    [Fact]
    public void Analyze_PublicAndInternalTypes_ReportsVisibility()
    {
        string directory = CreateFixture("""
            namespace Sample.App;

            public sealed class PublicHandler
            {
            }

            internal sealed class InternalHandler
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Contains(report.Components, component =>
            component.Name == "PublicHandler" && component.Visibility == Visibility.Public);
        Assert.Contains(report.Components, component =>
            component.Name == "InternalHandler" && component.Visibility == Visibility.Internal);
    }

    [Fact]
    public void Analyze_ObjectCreationAcrossNamespace_ReportsFunctionalDistanceAndIssue()
    {
        string directory = CreateFixture(
            "Api.cs",
            """
            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    _ = new Repository();
                }
            }
            """,
            "Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        CouplingMetrics coupling = Assert.Single(report.Couplings);
        Assert.Equal(IntegrationStrength.Functional, coupling.Strength);
        Assert.Equal(Distance.DifferentNamespace, coupling.Distance);
        Assert.Contains(report.Issues, issue => issue.Type == IssueType.GlobalComplexity);
    }

    [Fact]
    public void Analyze_CircularNamespaceDependency_ReportsCircularDependencyIssue()
    {
        string directory = CreateFixture(
            "First.cs",
            """
            namespace Sample.App.First;

            public sealed class FirstType
            {
                public SecondType? Second { get; init; }
            }
            """,
            "Second.cs",
            """
            namespace Sample.App.Second;

            public sealed class SecondType
            {
                public FirstType? First { get; init; }
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Contains(report.Issues, issue => issue.Type == IssueType.CircularDependency);
    }

    [Fact]
    public void Analyze_GeneratedFileNameAndHeader_ExcludesGeneratedCode()
    {
        string directory = CreateFixture(
            "Generated.g.cs",
            """
            namespace Sample.App;

            public sealed class GeneratedType
            {
            }
            """,
            "HeaderGenerated.cs",
            """
            // <auto-generated />
            namespace Sample.App;

            public sealed class HeaderGeneratedType
            {
            }
            """,
            "Real.cs",
            """
            namespace Sample.App;

            public sealed class RealType
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("RealType", component.Name);
    }

    [Fact]
    public void Analyze_ExternalUsingAcrossManyComponents_ReportsScatteredExternalCoupling()
    {
        string directory = CreateFixture(
            "First.cs",
            ExternalUsingSource("First"),
            "Second.cs",
            ExternalUsingSource("Second"),
            "Third.cs",
            ExternalUsingSource("Third"),
            "Fourth.cs",
            ExternalUsingSource("Fourth"),
            "Fifth.cs",
            ExternalUsingSource("Fifth"));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(5, report.Summary.ExternalCouplings);
        Assert.Contains(report.Issues, issue =>
            issue.Type == IssueType.ScatteredExternalCoupling
            && issue.Target == "Newtonsoft.Json");
    }

    [Fact]
    public void Analyze_ConfigExcludePathPattern_RemovesMatchingFilesFromAnalysis()
    {
        string directory = CreateFixture(
            "Kept.cs",
            """
            namespace Sample.App;

            public sealed class Kept
            {
            }
            """,
            "Ignored.cs",
            """
            namespace Sample.App;

            public sealed class Ignored
            {
            }
            """);
        AnalysisOptions options = AnalysisOptions.Default with
        {
            ExcludePathPatterns = ["**/Ignored.cs"],
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Component component = Assert.Single(report.Components);
        Assert.Equal("Kept", component.Name);
    }

    [Fact]
    public void Analyze_ConfigScatteredExternalThreshold_ChangesIssueBoundary()
    {
        string directory = CreateFixture(
            "First.cs",
            ExternalUsingSource("First"),
            "Second.cs",
            ExternalUsingSource("Second"));
        AnalysisOptions options = AnalysisOptions.Default with
        {
            Thresholds = AnalysisOptions.Default.Thresholds with { ScatteredExternalBreadth = 2 },
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Assert.Contains(report.Issues, issue => issue.Type == IssueType.ScatteredExternalCoupling);
    }

    [Fact]
    public void Analyze_ConfigIgnoreIssueType_RemovesIssueBeforeGradeCalculation()
    {
        string directory = CreateFixture(
            "Api.cs",
            """
            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    _ = new Repository();
                }
            }
            """,
            "Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
            }
            """);
        AnalysisOptions options = AnalysisOptions.Default with
        {
            IgnoreIssueTypes = new HashSet<IssueType> { IssueType.GlobalComplexity },
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Assert.DoesNotContain(report.Issues, issue => issue.Type == IssueType.GlobalComplexity);
        Assert.Equal("B", report.Grade.Letter);
    }

    [Fact]
    public void Analyze_NamespaceScopedExternalUsingAcrossManyComponents_ReportsScatteredExternalCoupling()
    {
        string directory = CreateFixture(
            "First.cs",
            NamespaceScopedExternalUsingSource("First"),
            "Second.cs",
            NamespaceScopedExternalUsingSource("Second"),
            "Third.cs",
            NamespaceScopedExternalUsingSource("Third"),
            "Fourth.cs",
            NamespaceScopedExternalUsingSource("Fourth"),
            "Fifth.cs",
            NamespaceScopedExternalUsingSource("Fifth"));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(5, report.Summary.ExternalCouplings);
        Assert.Contains(report.Issues, issue =>
            issue.Type == IssueType.ScatteredExternalCoupling
            && issue.Target == "Newtonsoft.Json");
    }

    private static string CreateFixture(string source)
    {
        return CreateFixture("Sample.cs", source);
    }

    private static string CreateFixture(params string[] fileNamesAndSources)
    {
        string directory = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        for (int i = 0; i < fileNamesAndSources.Length; i += 2)
        {
            File.WriteAllText(Path.Combine(directory, fileNamesAndSources[i]), fileNamesAndSources[i + 1]);
        }

        return directory;
    }

    private static string ExternalUsingSource(string typeName)
    {
        return $$"""
            using Newtonsoft.Json;

            namespace Sample.App.{{typeName}};

            public sealed class {{typeName}}
            {
            }
            """;
    }

    private static string NamespaceScopedExternalUsingSource(string typeName)
    {
        return $$"""
            namespace Sample.App.{{typeName}}
            {
                using Newtonsoft.Json;

                public sealed class {{typeName}}
                {
                }
            }
            """;
    }
}
