using DotnetCoupling.Core;
using DotnetCoupling.Git;
using DotnetCoupling.Roslyn;
using Xunit;

namespace DotnetCoupling.Tests;

public sealed class CSharpDependencyAnalyzerTests
{
    [Fact]
    public void Analyze_TwoTypesWithConstructorDependency_ReportsComponentAndCoupling()
    {
        string directory = CreateFixture("""
            namespace Sample.App;

            public sealed class Handler
            {
                public Handler(IRepository repository)
                {
                }
            }

            public interface IRepository
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(2, report.Components.Count);
        Assert.Contains(report.Couplings, coupling =>
            coupling.Source == "Sample.App.Handler"
            && coupling.Target == "Sample.App.IRepository"
            && coupling.Strength == IntegrationStrength.Contract);
    }

    [Fact]
    public void Analyze_PublicAndInternalTypes_ReportsVisibility()
    {
        string directory = CreateFixture("""
            namespace Sample.App;

            public sealed class PublicHandler
            {
            }

            internal sealed class InternalHandler
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Contains(report.Components, component =>
            component.Name == "PublicHandler" && component.Visibility == Visibility.Public);
        Assert.Contains(report.Components, component =>
            component.Name == "InternalHandler" && component.Visibility == Visibility.Internal);
    }

    [Fact]
    public void Analyze_ObjectCreationAcrossNamespace_ReportsFunctionalDistanceAndIssue()
    {
        string directory = CreateFixture(
            "Api.cs",
            """
            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    _ = new Repository();
                }
            }
            """,
            "Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        CouplingMetrics coupling = Assert.Single(report.Couplings);
        Assert.Equal(IntegrationStrength.Functional, coupling.Strength);
        Assert.Equal(Distance.DifferentNamespace, coupling.Distance);
        Assert.Contains(report.Issues, issue => issue.Type == IssueType.GlobalComplexity);
    }

    [Fact]
    public void Analyze_CircularNamespaceDependency_ReportsCircularDependencyIssue()
    {
        string directory = CreateFixture(
            "First.cs",
            """
            namespace Sample.App.First;

            public sealed class FirstType
            {
                public SecondType? Second { get; init; }
            }
            """,
            "Second.cs",
            """
            namespace Sample.App.Second;

            public sealed class SecondType
            {
                public FirstType? First { get; init; }
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Contains(report.Issues, issue => issue.Type == IssueType.CircularDependency);
    }

    [Fact]
    public void Analyze_GeneratedFileNameAndHeader_ExcludesGeneratedCode()
    {
        string directory = CreateFixture(
            "Generated.g.cs",
            """
            namespace Sample.App;

            public sealed class GeneratedType
            {
            }
            """,
            "HeaderGenerated.cs",
            """
            // <auto-generated />
            namespace Sample.App;

            public sealed class HeaderGeneratedType
            {
            }
            """,
            "Real.cs",
            """
            namespace Sample.App;

            public sealed class RealType
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("RealType", component.Name);
    }

    [Fact]
    public void Analyze_SlnxInput_WithMissingReferencedProject_ContinuesAndReportsDiagnostic()
    {
        string root = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        string app = Path.Combine(root, "App");
        Directory.CreateDirectory(app);
        File.WriteAllText(
            Path.Combine(root, "Sample.slnx"),
            """
            <Solution>
              <Project Path="App/App.csproj" />
            </Solution>
            """);
        File.WriteAllText(
            Path.Combine(app, "App.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
              <ItemGroup>
                <ProjectReference Include="../Missing/Missing.csproj" />
              </ItemGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(app, "Handler.cs"),
            """
            namespace Sample.App;

            public sealed class Handler
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(Path.Combine(root, "Sample.slnx"), useGit: false, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("App", component.ProjectName);
        AnalysisDiagnostic diagnostic = Assert.Single(report.Diagnostics!);
        Assert.Equal("missing-project-reference", diagnostic.Code);
    }

    [Fact]
    public void Analyze_SlnxInput_WithInvalidProject_ContinuesAndReportsDiagnostic()
    {
        string root = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        string app = Path.Combine(root, "App");
        string broken = Path.Combine(root, "Broken");
        Directory.CreateDirectory(app);
        Directory.CreateDirectory(broken);
        File.WriteAllText(
            Path.Combine(root, "Sample.slnx"),
            """
            <Solution>
              <Project Path="App/App.csproj" />
              <Project Path="Broken/Broken.csproj" />
            </Solution>
            """);
        File.WriteAllText(
            Path.Combine(app, "App.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(app, "Handler.cs"),
            """
            namespace Sample.App;

            public sealed class Handler
            {
            }
            """);
        File.WriteAllText(Path.Combine(broken, "Broken.csproj"), "<Project><PropertyGroup>");

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(Path.Combine(root, "Sample.slnx"), useGit: false, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("App", component.ProjectName);
        AnalysisDiagnostic diagnostic = Assert.Single(report.Diagnostics!);
        Assert.Equal("invalid-project", diagnostic.Code);
    }

    [Fact]
    public void Analyze_SemanticMode_SlnxInput_LoadsProjectsAndCouplings()
    {
        string root = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        string app = Path.Combine(root, "App");
        string domain = Path.Combine(root, "Domain");
        Directory.CreateDirectory(app);
        Directory.CreateDirectory(domain);
        File.WriteAllText(
            Path.Combine(root, "Sample.slnx"),
            """
            <Solution>
              <Project Path="App/App.csproj" />
              <Project Path="Domain/Domain.csproj" />
            </Solution>
            """);
        File.WriteAllText(
            Path.Combine(app, "App.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
              <ItemGroup>
                <ProjectReference Include="../Domain/Domain.csproj" />
              </ItemGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(domain, "Domain.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(app, "Handler.cs"),
            """
            namespace Sample.App;

            public sealed class Handler
            {
                public Entity Entity { get; } = new();
            }
            """);
        File.WriteAllText(
            Path.Combine(domain, "Entity.cs"),
            """
            namespace Sample.Domain;

            public sealed class Entity
            {
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(Path.Combine(root, "Sample.slnx"), AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.Equal("semantic-preview", report.Summary.Mode);
        Assert.Equal(2, report.Components.Count);
        Assert.Contains(report.Couplings, coupling =>
            coupling.Source == "Sample.App.Handler"
            && coupling.Target == "Sample.Domain.Entity"
            && coupling.Distance == Distance.DifferentProject);
    }

    [Fact]
    public void Analyze_SemanticMode_SlnxInput_WithInvalidProject_ContinuesAndReportsDiagnostic()
    {
        string root = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        string app = Path.Combine(root, "App");
        string broken = Path.Combine(root, "Broken");
        Directory.CreateDirectory(app);
        Directory.CreateDirectory(broken);
        File.WriteAllText(
            Path.Combine(root, "Sample.slnx"),
            """
            <Solution>
              <Project Path="App/App.csproj" />
              <Project Path="Broken/Broken.csproj" />
            </Solution>
            """);
        File.WriteAllText(
            Path.Combine(app, "App.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(app, "Handler.cs"),
            """
            namespace Sample.App;

            public sealed class Handler
            {
            }
            """);
        File.WriteAllText(Path.Combine(broken, "Broken.csproj"), "<Project><PropertyGroup>");

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(
            Path.Combine(root, "Sample.slnx"),
            AnalysisMode.Semantic,
            volatilityProvider: null,
            gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("App", component.ProjectName);
        Assert.Contains(report.Diagnostics!, diagnostic => diagnostic.Code == "invalid-project");
    }

    [Fact]
    public void Analyze_SemanticMode_SlnInput_WithInvalidProject_ContinuesAndReportsDiagnostic()
    {
        string root = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        string app = Path.Combine(root, "App");
        string broken = Path.Combine(root, "Broken");
        Directory.CreateDirectory(app);
        Directory.CreateDirectory(broken);
        File.WriteAllText(
            Path.Combine(root, "Sample.sln"),
            """
            Microsoft Visual Studio Solution File, Format Version 12.00
            # Visual Studio Version 17
            VisualStudioVersion = 17.0.31903.59
            MinimumVisualStudioVersion = 10.0.40219.1
            Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "App", "App\App.csproj", "{11111111-1111-1111-1111-111111111111}"
            EndProject
            Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Broken", "Broken\Broken.csproj", "{22222222-2222-2222-2222-222222222222}"
            EndProject
            Global
            EndGlobal
            """);
        File.WriteAllText(
            Path.Combine(app, "App.csproj"),
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """);
        File.WriteAllText(
            Path.Combine(app, "Handler.cs"),
            """
            namespace Sample.App;

            public sealed class Handler
            {
            }
            """);
        File.WriteAllText(Path.Combine(broken, "Broken.csproj"), "<Project><PropertyGroup>");

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(
            Path.Combine(root, "Sample.sln"),
            AnalysisMode.Semantic,
            volatilityProvider: null,
            gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("App", component.ProjectName);
        Assert.NotEmpty(report.Diagnostics!);
    }

    [Fact]
    public void Analyze_ExternalUsingAcrossManyComponents_ReportsScatteredExternalCoupling()
    {
        string directory = CreateFixture(
            "First.cs",
            ExternalUsingSource("First"),
            "Second.cs",
            ExternalUsingSource("Second"),
            "Third.cs",
            ExternalUsingSource("Third"),
            "Fourth.cs",
            ExternalUsingSource("Fourth"),
            "Fifth.cs",
            ExternalUsingSource("Fifth"));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(5, report.Summary.ExternalCouplings);
        Assert.Contains(report.Issues, issue =>
            issue.Type == IssueType.ScatteredExternalCoupling
            && issue.Target == "Newtonsoft.Json");
    }

    [Fact]
    public void Analyze_ConfigExcludePathPattern_RemovesMatchingFilesFromAnalysis()
    {
        string directory = CreateFixture(
            "Kept.cs",
            """
            namespace Sample.App;

            public sealed class Kept
            {
            }
            """,
            "Ignored.cs",
            """
            namespace Sample.App;

            public sealed class Ignored
            {
            }
            """);
        AnalysisOptions options = AnalysisOptions.Default with
        {
            ExcludePathPatterns = ["**/Ignored.cs"],
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Component component = Assert.Single(report.Components);
        Assert.Equal("Kept", component.Name);
    }

    [Fact]
    public void Analyze_ConfigScatteredExternalThreshold_ChangesIssueBoundary()
    {
        string directory = CreateFixture(
            "First.cs",
            ExternalUsingSource("First"),
            "Second.cs",
            ExternalUsingSource("Second"));
        AnalysisOptions options = AnalysisOptions.Default with
        {
            Thresholds = AnalysisOptions.Default.Thresholds with { ScatteredExternalBreadth = 2 },
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Assert.Contains(report.Issues, issue => issue.Type == IssueType.ScatteredExternalCoupling);
    }

    [Fact]
    public void Analyze_ConfigIgnoreIssueType_RemovesIssueBeforeGradeCalculation()
    {
        string directory = CreateFixture(
            "Api.cs",
            """
            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    _ = new Repository();
                }
            }
            """,
            "Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
            }
            """);
        AnalysisOptions options = AnalysisOptions.Default with
        {
            IgnoreIssueTypes = new HashSet<IssueType> { IssueType.GlobalComplexity },
        };

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6, options);

        Assert.DoesNotContain(report.Issues, issue => issue.Type == IssueType.GlobalComplexity);
        Assert.Equal("B", report.Grade.Letter);
    }

    [Fact]
    public void Analyze_NamespaceScopedExternalUsingAcrossManyComponents_ReportsScatteredExternalCoupling()
    {
        string directory = CreateFixture(
            "First.cs",
            NamespaceScopedExternalUsingSource("First"),
            "Second.cs",
            NamespaceScopedExternalUsingSource("Second"),
            "Third.cs",
            NamespaceScopedExternalUsingSource("Third"),
            "Fourth.cs",
            NamespaceScopedExternalUsingSource("Fourth"),
            "Fifth.cs",
            NamespaceScopedExternalUsingSource("Fifth"));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Equal(5, report.Summary.ExternalCouplings);
        Assert.Contains(report.Issues, issue =>
            issue.Type == IssueType.ScatteredExternalCoupling
            && issue.Target == "Newtonsoft.Json");
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesGlobalUsingAliasToInternalType()
    {
        string projectPath = CreateProjectFixture(
            ("GlobalUsings.cs",
            """
            global using InfraRepo = Sample.App.Infrastructure.Repository;
            """),
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    _ = new InfraRepo();
                }
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Couplings, coupling => coupling.Source == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Couplings, coupling =>
            coupling.Source == "Sample.App.Api.Handler"
            && coupling.Target == "Sample.App.Infrastructure.Repository"
            && coupling.Strength == IntegrationStrength.Functional);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesAttributeTypeToContainingType()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            [RepositoryMarker]
            public sealed class Handler
            {
            }
            """),
            ("RepositoryMarkerAttribute.cs",
            """
            namespace Sample.App.Infrastructure;

            [System.AttributeUsage(System.AttributeTargets.Class)]
            public sealed class RepositoryMarkerAttribute : System.Attribute
            {
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation => observation.SourceComponentId == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryMarkerAttribute"
            && observation.Usage == UsageContext.Attribute
            && observation.Kind == DependencyKind.Attribute);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesStaticPropertyAccessToContainingType()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public object? Handle()
                {
                    return RepositoryCatalog.Shared;
                }
            }
            """),
            ("RepositoryCatalog.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class RepositoryCatalog
            {
                public static object Shared { get; } = new();
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation => observation.SourceComponentId == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryCatalog"
            && observation.Usage == UsageContext.PropertyAccess
            && observation.Kind == DependencyKind.PropertyAccess);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesStaticMethodInvocationToContainingType()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    RepositoryCatalog.Reset();
                }
            }
            """),
            ("RepositoryCatalog.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class RepositoryCatalog
            {
                public static void Reset()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation => observation.SourceComponentId == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryCatalog"
            && observation.Usage == UsageContext.StaticCall
            && observation.Kind == DependencyKind.StaticCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesChainedInvocationToContainingTypes()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    RepositoryFactory.Create().Save();
                }
            }
            """),
            ("RepositoryFactory.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class RepositoryFactory
            {
                public static Repository Create()
                {
                    return new Repository();
                }
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
                public void Save()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation => observation.SourceComponentId == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryFactory"
            && observation.Usage == UsageContext.StaticCall
            && observation.Kind == DependencyKind.StaticCall);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.Repository"
            && observation.Usage == UsageContext.MethodCall
            && observation.Kind == DependencyKind.MethodCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesInstancePropertyAccessAndInvocation()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                private readonly RepositoryHolder _holder = new();

                public void Handle()
                {
                    _holder.Repository.Save();
                }
            }
            """),
            ("RepositoryHolder.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class RepositoryHolder
            {
                public Repository Repository { get; } = new();
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
                public void Save()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.Usage == UsageContext.PropertyAccess);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryHolder"
            && observation.Usage == UsageContext.PropertyAccess
            && observation.Kind == DependencyKind.PropertyAccess);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.Repository"
            && observation.Usage == UsageContext.MethodCall
            && observation.Kind == DependencyKind.MethodCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesInstanceFieldAccessAndInvocation()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                private readonly RepositoryHolder _holder = new();

                public void Handle()
                {
                    _holder.Repository.Save();
                }
            }
            """),
            ("RepositoryHolder.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class RepositoryHolder
            {
                public readonly Repository Repository = new();
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
                public void Save()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.Usage == UsageContext.FieldAccess);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryHolder"
            && observation.Usage == UsageContext.FieldAccess
            && observation.Kind == DependencyKind.FieldAccess);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.Repository"
            && observation.Usage == UsageContext.MethodCall
            && observation.Kind == DependencyKind.MethodCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesExtensionMethodInvocationToExtensionType()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Domain;
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    new Entity().Persist();
                }
            }
            """),
            ("Entity.cs",
            """
            namespace Sample.App.Domain;

            public sealed class Entity
            {
            }
            """),
            ("PersistenceExtensions.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class PersistenceExtensions
            {
                public static void Persist(this Sample.App.Domain.Entity entity)
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.Usage == UsageContext.StaticCall);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.PersistenceExtensions"
            && observation.Usage == UsageContext.StaticCall
            && observation.Kind == DependencyKind.StaticCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesConditionalAccessInvocationToContainingType()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                private readonly Repository? _repository = new();

                public void Handle()
                {
                    _repository?.Save();
                }
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
                public void Save()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.Usage == UsageContext.MethodCall);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.Repository"
            && observation.Usage == UsageContext.MethodCall
            && observation.Kind == DependencyKind.MethodCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesGenericReturnChainedInvocationToContainingTypes()
    {
        string projectPath = CreateProjectFixture(
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    RepositoryFactory.Create<Repository>().Save();
                }
            }
            """),
            ("RepositoryFactory.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class RepositoryFactory
            {
                public static T Create<T>() where T : new()
                {
                    return new T();
                }
            }
            """),
            ("Repository.cs",
            """
            namespace Sample.App.Infrastructure;

            public sealed class Repository
            {
                public void Save()
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation => observation.SourceComponentId == "Sample.App.Api.Handler");
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.RepositoryFactory"
            && observation.Usage == UsageContext.StaticCall
            && observation.Kind == DependencyKind.StaticCall);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.Repository"
            && observation.Usage == UsageContext.MethodCall
            && observation.Kind == DependencyKind.MethodCall);
    }

    [Fact]
    public void Analyze_SemanticMode_ResolvesAliasQualifiedExtensionMethodInvocation()
    {
        string projectPath = CreateProjectFixture(
            ("GlobalUsings.cs",
            """
            global using DomainEntity = Sample.App.Domain.Entity;
            """),
            ("Handler.cs",
            """
            using Sample.App.Infrastructure;

            namespace Sample.App.Api;

            public sealed class Handler
            {
                public void Handle()
                {
                    new DomainEntity().Persist();
                }
            }
            """),
            ("Entity.cs",
            """
            namespace Sample.App.Domain;

            public sealed class Entity
            {
            }
            """),
            ("PersistenceExtensions.cs",
            """
            namespace Sample.App.Infrastructure;

            public static class PersistenceExtensions
            {
                public static void Persist(this Sample.App.Domain.Entity entity)
                {
                }
            }
            """));

        AnalysisReport syntaxReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Syntax, volatilityProvider: null, gitMonths: 6);
        AnalysisReport semanticReport = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.DoesNotContain(syntaxReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.Usage == UsageContext.StaticCall);
        Assert.Contains(semanticReport.Observations, observation =>
            observation.SourceComponentId == "Sample.App.Api.Handler"
            && observation.TargetName == "Sample.App.Infrastructure.PersistenceExtensions"
            && observation.Usage == UsageContext.StaticCall
            && observation.Kind == DependencyKind.StaticCall);
    }

    [Fact]
    public void Analyze_PartialTypeAcrossFiles_MergesLogicalComponent()
    {
        string directory = CreateFixture(
            "GuardAgainstNull.cs",
            """
            namespace Ardalis.GuardClauses;

            public static partial class GuardClauseExtensions
            {
                public static void Null(string value)
                {
                }
            }
            """,
            "GuardAgainstEmpty.cs",
            """
            namespace Ardalis.GuardClauses;

            public static partial class GuardClauseExtensions
            {
                public static void Empty(string value)
                {
                }
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("Ardalis.GuardClauses.GuardClauseExtensions", component.Id);
        Assert.Equal("GuardClauseExtensions", component.Name);
    }

    [Fact]
    public void Analyze_SemanticMode_PartialTypeAcrossFiles_MergesLogicalComponent()
    {
        string projectPath = CreateProjectFixture(
            ("GuardAgainstNull.cs",
            """
            namespace Ardalis.GuardClauses;

            public static partial class GuardClauseExtensions
            {
                public static void Null(string value)
                {
                }
            }
            """),
            ("GuardAgainstEmpty.cs",
            """
            namespace Ardalis.GuardClauses;

            public static partial class GuardClauseExtensions
            {
                public static void Empty(string value)
                {
                }
            }
            """));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Component component = Assert.Single(report.Components);
        Assert.Equal("Ardalis.GuardClauses.GuardClauseExtensions", component.Id);
        Assert.Equal("GuardClauseExtensions", component.Name);
    }

    [Fact]
    public void Analyze_GenericAndNonGenericTypesWithSameName_UsesDistinctComponents()
    {
        string directory = CreateFixture("""
            namespace CSharpx;

            internal abstract class Either<TLeft, TRight>
            {
            }

            internal static class Either
            {
                public static Either<string, int>? Create()
                {
                    return null;
                }
            }
            """);

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(directory, useGit: false, gitMonths: 6);

        Assert.Contains(report.Components, component => component.Id == "CSharpx.Either`2");
        Assert.Contains(report.Components, component => component.Id == "CSharpx.Either");
        Assert.Equal(2, report.Components.Count);
    }

    [Fact]
    public void Analyze_SemanticMode_GenericAndNonGenericTypesWithSameName_UsesDistinctComponents()
    {
        string projectPath = CreateProjectFixture(
            ("Either.Generic.cs",
            """
            namespace CSharpx;

            internal abstract partial class Either<TLeft, TRight>
            {
            }
            """),
            ("Either.Generic.Partial.cs",
            """
            namespace CSharpx;

            internal abstract partial class Either<TLeft, TRight>
            {
            }
            """),
            ("Either.cs",
            """
            namespace CSharpx;

            internal static class Either
            {
                public static Either<string, int>? Create()
                {
                    return null;
                }
            }
            """));

        AnalysisReport report = CSharpDependencyAnalyzer.Analyze(projectPath, AnalysisMode.Semantic, volatilityProvider: null, gitMonths: 6);

        Assert.Contains(report.Components, component => component.Id == "CSharpx.Either`2");
        Assert.Contains(report.Components, component => component.Id == "CSharpx.Either");
        Assert.Equal(2, report.Components.Count);
        Assert.Contains(report.Couplings, coupling =>
            coupling.Source == "CSharpx.Either"
            && coupling.Target == "CSharpx.Either`2");
    }

    private static string CreateFixture(string source)
    {
        return CreateFixture("Sample.cs", source);
    }

    private static string CreateFixture(params string[] fileNamesAndSources)
    {
        string directory = Path.Combine(Path.GetTempPath(), "dotnet-coupling-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        for (int i = 0; i < fileNamesAndSources.Length; i += 2)
        {
            File.WriteAllText(Path.Combine(directory, fileNamesAndSources[i]), fileNamesAndSources[i + 1]);
        }

        return directory;
    }

    private static string CreateProjectFixture(params (string FileName, string Source)[] files)
    {
        string directory = CreateFixture([]);
        string projectPath = Path.Combine(directory, "Sample.App.csproj");
        File.WriteAllText(
            projectPath,
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """);

        foreach ((string fileName, string source) in files)
        {
            File.WriteAllText(Path.Combine(directory, fileName), source);
        }

        return projectPath;
    }

    private static string ExternalUsingSource(string typeName)
    {
        return $$"""
            using Newtonsoft.Json;

            namespace Sample.App.{{typeName}};

            public sealed class {{typeName}}
            {
            }
            """;
    }

    private static string NamespaceScopedExternalUsingSource(string typeName)
    {
        return $$"""
            namespace Sample.App.{{typeName}}
            {
                using Newtonsoft.Json;

                public sealed class {{typeName}}
                {
                }
            }
            """;
    }
}
